name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Or your default branch name
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/stock-rss:latest
          docker build -t $IMAGE_NAME .

      - name: Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/stock-rss:latest
          docker push $IMAGE_NAME

